batch_size: 128
buffer_size: 50000
num_epochs: 200
hidden_size: 100
img_height: 32
img_width: 32
num_channels: 3
checkpoint_step: 10
learning_rate_generator: 0.0005
learning_rate_discriminator: 0.0005
save_images_every_n_steps: 100